#return children ready for HyperNEAT generation


def GetNextChildrenHyperNEAT(endtime)
#This function returns rows of children that are ready to be generated by HyperNEAT: ChildID, firstID, secondID
	import MySQLdb
	mdb = MySQLdb.connect(...)
	cur = mdb.cursor()

	#Get all children from table NewChildren that have to be generated
	cur.execute("SELECT CAST(ChildID AS nvarchar(9))+'.xml' As ChildID, CAST(ParentOne AS nvarchar(9))+'.xml' AS ParentOne, CAST(ParentTwo AS nvarchar(9))+'.xml' AS ParentTwo FROM NewChildren WHERE HNeat = 0 AND timestep < %s", endtime)
	children = cur.fetchall()
	
	#Update the RobotLocationData table with the HyperNeat marker for the children
	cur.execute("UPDATE RobotLocationData SET HNeat = 1 WHERE RobotID IN (SELECT ChildID FROM NewChildren WHERE HNeat = 0 AND timestep < %s)", endtime)

	#Update Hyperneat marker for all children that were returned by the last statement
	cur.exectue("UPDATE NewChildData SET HNeat = 1 WHERE HNeat = 0 AND timestep < %s", endtime)

	cur.close()
	mdb.close()

	return children