#return children ready for VoxCad simulation


def GetNextChildrenVoxCad(endtime)
#This function returns rows of children that are ready to be simulated: RobotID, timestep, x, y, z
	import MySQLdb
	mdb = MySQLdb.connect(...)
	cur = mdb.cursor()

	#Select all children (child = 1) that have been generated by hyperneat (HNeat = 1), but have not been simulated yet (VCad = 0)
	cur.execute("SELECT CAST(RobotID AS nvarchar(9))+'.xml' AS RobotID, timestep, x, y, z FROM RobotLocationData WHERE timestep < %s AND child = 1 AND HNeat = 1 AND VCad = 0", endtime)
	childrenVoxCad = cur.fetchall()

	cur.close()
	mdb.close()

	return childrenVoxCad