#return children ready for HyperNEAT generation


def GetNextChildrenHyperNEAT(endtime)
#This function returns rows of children that are ready to be generated by HyperNEAT: ChildID, firstID, secondID, timestep
	import MySQLdb
	mdb = MySQLdb.connect(...)
	cur = mdb.cursor()

	cur.execute("SELECT ChildID, firstID, secondID, timestep FROM NewChildData WHERE timestep < endtime")
	children = cur.fetchall()
	cur.exectue("DELETE FROM NewChildData WHERE timestep < endtime")

	cur.close()
	mdb.close()

	return children