
#Data expectation: ID, timestep, x, y, z

def InputSimulatedChildren (data):
#Input the children ready for simulation that have been generated by HyperNEAT

	import MySQLdb
 	mdb = MySQLdb.connect(...)
 	cur = mdb.cursor()	

	for row in data:
		#change parts of the code to fit in the data parameter
		cur.execute("INSERT INTO SimulateChildData (ChildID, timestep, x, y, z) VALUES (%s,%s,%d,%d,%d,%s)", (row[0],row[1],row[2],row[3],row[4]))

	cur.close()
	mdb.close()